# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13623a80d6b8d97507229ba5408255eebfcf244b6d321dde7ae833ab221c9a04742db4eab427fcde133d3b0059c207d3bba7d7c3eb91080a32f91fa79d5cf285

test:
  secret_key_base: a9ba43446ffad030f97b532331fbf22a5d5e5beccb6e886a6e921bd7ee55ce0ffc63261417b0c0905e08e5560421911ad97728ce8c96ebdb487052a5aa1e9c21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
